project_name: memory-hc

before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - linux
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
release:
  draft: true
archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
      linux: Linux
      freebsd: FreeBSD
      openbsd: OpenBSD
      netbsd: NetBSD
      windows: Windows
      386: i386
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
